version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.0
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
          - 	"d0:12:6d:86:9d:31:1b:a4:41:9f:cc:a7:c4:66:f6:0d"
